#!/usr/bin/env node
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { chromium } from 'playwright-core';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const base = process.argv[2] ?? 'http://127.0.0.1:8642/';
const read = file => JSON.parse(fs.readFileSync(path.join(ROOT, file), 'utf8'));
const card = read('visbybuild/reference/club-scorecard.json');
const meta = read('apps/golf/src/data/visby-preview.json');
const bundled = chromium.executablePath();
const browser = await chromium.launch(fs.existsSync(bundled) ? { executablePath: bundled } : { channel: 'chrome' });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
const page = await context.newPage(), requests = [], errors = [];
page.on('pageerror', error => errors.push(error.message));
page.on('request', request => requests.push(request.url()));
const report = { groundId: 'visby', previewSha256: meta.previewSha256, checkedAt: new Date().toISOString(), base, browser: browser.version(), checks: [] };
try {
  await page.goto(new URL('?bana=visby&view=sources', base).href);
  await page.locator('.intake-card tbody tr').last().waitFor();
  assert.match(await page.title(), /Visby/);
  const rows = await page.locator('.intake-card tbody tr').evaluateAll(rows => rows.map(row => [...row.children].map(cell => Number(cell.textContent))));
  assert.deepEqual(rows, card.holes.map(h => [h.number, h.par, h.index, ...card.tees.map(t => h.lengths[t.id])]));
  assert.equal(await page.locator('.intake-route').count(), 0);
  assert.equal(await page.locator('#intakeSurfaceLayer path').count(), 25);
  await page.locator('.intake-hole-buttons [data-hole="18"]').click();
  assert.match(page.url(), /hal=18/);
  assert.match(await page.locator('#intakeHole').innerText(), /ännu inte tillgänglig/);
  await page.locator('#intakeSurfaces').uncheck();
  assert.equal(await page.locator('#intakeSurfaceLayer').getAttribute('visibility'), 'hidden');
  await page.locator('#intakeSurfaces').check();
  assert.ok(!requests.some(url => /\.(?:gpk|bvch)(?:\?|$)|\/assets\/main-|three\.(?:core|tsl)/.test(url)), 'source preview must not download a playable course or 3D engine');
  report.checks.push('desktop card: all 162 cells match source; 25 polygons; unresolved routing stays unavailable; hole selection and layer toggle; no 3D payload');
  fs.mkdirSync(path.join(ROOT, 'visbybuild/shots'), { recursive: true });
  await page.screenshot({ path: path.join(ROOT, 'visbybuild/shots/intake-desktop.png'), fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 1), 'mobile body must not overflow');
  await page.screenshot({ path: path.join(ROOT, 'visbybuild/shots/intake-mobile.png'), fullPage: true });
  report.checks.push('390px mobile layout: no page overflow; six tee columns scroll inside scorecard');
  await page.evaluate(async () => { await navigator.serviceWorker.ready; });
  await page.reload();
  await page.locator('.intake-card tbody tr').last().waitFor();
  await context.setOffline(true);
  await page.reload();
  await page.locator('.intake-card tbody tr').last().waitFor();
  assert.match(await page.title(), /Visby/);
  report.checks.push('visited production preview reopens offline with verified intake');
  await context.setOffline(false);
  await page.setViewportSize({ width: 1440, height: 1000 });
  await page.goto(new URL('?bana=lidingo&hal=18&view=sources', base).href);
  await page.locator('.intake-card tbody tr').last().waitFor();
  assert.equal(await page.locator('.intake-route').count(), 18);
  assert.equal(await page.locator('.intake-card thead th').count(), 8);
  assert.match(await page.locator('#courseIntake h1').innerText(), /Lidingö/);
  report.checks.push('Lidingö regression: 18 routes, five tees, correct course identity');
  await page.goto(base);
  await page.locator('button.card[data-slug="visby"]').waitFor();
  await page.locator('#courseSearchInput').fill('Visby');
  assert.equal(await page.locator('.card-item:visible').count(), 1);
  report.checks.push('chooser search finds the Visby course; 3D navigation verified by check-runtime');
  await page.goto(new URL('?bana=visby&view=sources&v2=require', base).href);
  assert.match(await page.locator('#courseIntake [role="status"]').innerText(), /^Visby GK: den här adressen visar källkartan/);
  assert.equal(await page.locator('.intake-card').count(), 0);
  report.checks.push('source view explains how to open the separate provisional 3D course');
  assert.deepEqual(errors, []);
  report.pageErrors = errors;
  report.state = 'passed';
  fs.writeFileSync(path.join(ROOT, 'visbybuild/mapping/browser-validation.json'), JSON.stringify(report, null, 2) + '\n');
  console.log(JSON.stringify(report, null, 2));
} finally { await browser.close(); }
