/* Bind seven isolated Blender exports to existing source buildings. The pack,
 * terrain and previously published clubhouse remain independent inputs. */
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { readPack, inflateStream } from '../../packages/course-pack/lib.mjs';
import { inspectBuildingGlb } from '../../apps/golf/src/engine/authored-buildings.mjs';
import { authoredBuildings as clubhouse } from '../../apps/golf/src/engine/scenery/tortuna-architecture.js';

const root = fileURLToPath(new URL('../../', import.meta.url));
const read = relative => fs.readFileSync(path.join(root, relative));
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const pins = {
  'way/1163533128': '5e0420e9b3ea4182cb7bb81134db50a8beefefae4a80896f57c9f71aae7d5fe5',
  'tortuna-range-shelter': '13fc4312752ccb7c3044d8142c3bff8a7efb5ca5a227119c3ff7bb555d636700',
  'way/1163533113': '69ed0a0196d0057dce63243ffd8d3d4aba0c197c66eb05085406e953c05e5f68',
  'way/1163533114': '954d5de5fb8329f4eedc5d27909a21b6e81700570398acc18cdd1b62252665e0',
  'way/1163533115': 'bfcdbc7c8c2e35104ad2d0fe8c5df15d53c6acf3796ba628f32dd35d7178bfdc',
  'way/1163533123': '0ef780d25e28c986ae14fb57febad2474aec097110cd95a59deedb715cf2bd56',
  'way/1163607303': '853eacf28ce803a921300040f84c5290e2377932e2473ab3c59da4c57b1a0537',
};
const packBytes = read('apps/golf/public/courses/tortuna/pack.bin');
assert.equal(hash(packBytes), '746d8475e7aff2be389963331d5a9cef80cb7b056a7c6b8ca5d775b11b6c9931');
const model = JSON.parse(inflateStream(readPack(packBytes).sv));
assert.equal(clubhouse.length, 1);
assert.equal(hash(read(`apps/golf/public/${clubhouse[0].asset.url}`)), '1a78f59daa18e4474c8e0c5856d10a94acae7de36f7ffb9c75556fe1fb6b92b0');
const exported = JSON.parse(read('tortunabuild/facilities/model-export.json'));
assert.deepEqual(exported.buildings.map(b => b.buildingId).sort(), Object.keys(pins).sort());
const evidence = ['reference-review.md', 'reference-receipt.json', 'facility-geometry-evidence.json',
  'carpark-roof-fixture-evidence.json', 'model-parameters.json', 'appearance-parameters.json'].map(name => `tortunabuild/facilities/${name}`);
const descriptors = exported.buildings.map(row => {
  const source = model.infra.buildings.find(b => b.id === row.buildingId);
  assert.ok(source, row.buildingId);
  assert.equal(hash(JSON.stringify(source.ring)), pins[row.buildingId]);
  assert.equal(row.asset.url, `courses/tortuna/architecture/${row.asset.sha256}.glb`);
  const bytes = read(`apps/golf/public/${row.asset.url}`);
  assert.equal(bytes.length, row.asset.bytes);
  assert.equal(hash(bytes), row.asset.sha256);
  const glb = inspectBuildingGlb(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength));
  assert.equal(glb.scenes.length, 1);
  assert.equal(glb.meshes.length, row.meshes);
  assert.ok(glb.meshes.every(mesh => mesh.name.startsWith(`Tortuna facility | ${row.label} | `)));
  assert.ok(row.anchorEpsg3006RH2000.length === 3 && row.anchorEpsg3006RH2000.every(Number.isFinite));
  return { buildingId: row.buildingId, asset: row.asset, sourceFootprintSha256: pins[row.buildingId],
    anchorEpsg3006RH2000: row.anchorEpsg3006RH2000, courseOriginEpsg3006: [597400.5, 6614899.5],
    rotationYRadians: 0, scale: 1, appearanceStatus: row.appearanceStatus, evidence };
});
const descriptorPath = 'apps/golf/src/engine/scenery/tortuna-facilities.js';
fs.writeFileSync(path.join(root, descriptorPath), '// Generated by tortunabuild/facilities/publish-models.mjs after Blender review.\n'
  + `export const facilityBuildings = ${JSON.stringify(descriptors, null, 2)};\n`);
const receipt = { ...exported, sourcePackSha256: hash(packBytes), sourceGeometryChanged: false,
  retainedClubhouseSha256: clubhouse[0].asset.sha256,
  evidence: evidence.map(file => ({ file, sha256: hash(read(file)) })),
  sourceBuildings: exported.buildings.map(row => {
    const b = model.infra.buildings.find(b => b.id === row.buildingId);
    return { buildingId: b.id, sourceFootprintSha256: pins[b.id],
      sourceRoofSha256: b.roofSurface ? hash(JSON.stringify(b.roofSurface)) : null,
      sourceRoofTriangles: (b.roofSurface?.triangleIndices.length || 0) / 3 };
  }), generatedDescriptor: descriptorPath };
fs.writeFileSync(path.join(root, 'tortunabuild/facilities/published-models.json'), JSON.stringify(receipt, null, 2) + '\n');
console.log(`Published ${descriptors.length} facilities: ${exported.totalAssetBytes} bytes, ${exported.totals.triangles} triangles; source pack and clubhouse unchanged`);
