/* Bind a reviewed Blender export to the exact retained source building. This
 * display asset is separate from the measured course pack and terrain graph. */
import fs from 'node:fs';
import path from 'node:path';
import assert from 'node:assert/strict';
import { fileURLToPath } from 'node:url';
import { createHash } from 'node:crypto';
import { readPack, inflateStream } from '../../packages/course-pack/lib.mjs';
import { inspectBuildingGlb } from '../../apps/golf/src/engine/authored-buildings.mjs';

const root = fileURLToPath(new URL('../../', import.meta.url));
const read = relative => fs.readFileSync(path.join(root, relative));
const hash = bytes => createHash('sha256').update(bytes).digest('hex');
const modelExport = JSON.parse(read('tortunabuild/clubhouse/model-export.json'));
const bytes = read(`apps/golf/public/${modelExport.asset.url}`);
assert.equal(bytes.length, modelExport.asset.bytes);
assert.equal(hash(bytes), modelExport.asset.sha256);
const glb = inspectBuildingGlb(bytes.buffer.slice(bytes.byteOffset, bytes.byteOffset + bytes.byteLength));
assert.equal(glb.scenes.length, 1, 'Export only the dedicated architectural scene');
assert.equal(glb.meshes.length, modelExport.meshes);
assert.ok(glb.meshes.every(mesh => mesh.name.startsWith('Tortuna | ')), 'Unrelated Blender objects in export');
const packBytes = read('apps/golf/public/courses/tortuna/pack.bin');
const model = JSON.parse(inflateStream(readPack(packBytes).sv));
const building = model.infra.buildings.find(row => row.id === 'way/1163533127');
assert.ok(building?.roofSurface, 'Retained clubhouse source roof is required');
const footprintSha = hash(JSON.stringify(building.ring));
assert.equal(footprintSha, '12566507bd14acc1fd93c25fcea5691cac70fd483a6aef8783e13d861ce33e16');
const descriptors = [{ buildingId: building.id, asset: modelExport.asset,
  sourceFootprintSha256: footprintSha,
  anchorEpsg3006RH2000: modelExport.anchorEpsg3006RH2000,
  courseOriginEpsg3006: [597400.5, 6614899.5], rotationYRadians: 0, scale: 1,
  appearanceStatus: 'photo-informed-display-model',
  evidence: ['tortunabuild/clubhouse/reference-review.md', 'tortunabuild/clubhouse/geometry-evidence.json',
    'tortunabuild/clubhouse/model-parameters.json'] }];
fs.writeFileSync(path.join(root, 'apps/golf/src/engine/scenery/tortuna-architecture.js'),
  '// Generated by tortunabuild/clubhouse/publish-model.mjs after Blender review.\n'
  + `export const authoredBuildings = ${JSON.stringify(descriptors, null, 2)};\n`);
const evidence = { ...modelExport, sourcePackSha256: hash(packBytes), sourceFootprintSha256: footprintSha,
  sourceRoofSha256: hash(JSON.stringify(building.roofSurface)),
  sourceRoofTriangles: building.roofSurface.triangleIndices.length / 3,
  generatedDescriptor: 'apps/golf/src/engine/scenery/tortuna-architecture.js' };
fs.writeFileSync(path.join(root, 'tortunabuild/clubhouse/published-model.json'), JSON.stringify(evidence, null, 2) + '\n');
console.log(`Bound ${building.id}: ${modelExport.asset.bytes} bytes, ${modelExport.triangles} triangles; original source retained`);
