import fs from 'node:fs';
import path from 'node:path';
import {PAINTED_GROUND,AUTUMN_FOLIAGE,FOLIAGE_PALETTES} from '../../apps/golf/src/engine/painted-world-palette.mjs';
const out=path.resolve('docs/graphics/tree-palette-2026-09-13');
const swatches={Fairway:PAINTED_GROUND.fair,'Putting green':PAINTED_GROUND.green,Rough:PAINTED_GROUND.rough,
  Sand:PAINTED_GROUND.sand,Granite:PAINTED_GROUND.rock,Spruce:FOLIAGE_PALETTES.gran[1],Birch:FOLIAGE_PALETTES.bjork[1],
  Gold:AUTUMN_FOLIAGE.bjork.ramps[0][1],Orange:AUTUMN_FOLIAGE.bjork.ramps[1][1],Crimson:AUTUMN_FOLIAGE.ek.ramps[2][1]};
const chips=Object.entries(swatches).map(([label,hex])=>{const h='#'+hex.toString(16).padStart(6,'0');return `<div class="chip"><i style="background:${h}"></i><span>${label}<small>${h.toUpperCase()}</small></span></div>`;}).join('');
fs.writeFileSync(path.join(out,'index.html'),`<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Swedish golf · Witness-inspired colour review</title>
<style>
*{box-sizing:border-box}body{margin:0;background:#142827;color:#eee9d8;font:15px/1.55 system-ui,sans-serif}main{max-width:1660px;margin:auto;padding:36px 28px 60px}a{color:#edd28b;text-underline-offset:4px}.eyebrow{letter-spacing:.18em;font-size:11px;text-transform:uppercase;color:#b9bfa1}h1{font:clamp(30px,4vw,54px)/1.12 Georgia,serif;margin:12px 0}header p{max-width:820px;color:#c3cbbd}.toolbar{display:flex;gap:22px;align-items:end;flex-wrap:wrap;margin:28px 0 16px}label{display:grid;gap:5px;font-size:12px;color:#c3cbbd}select,button{background:#203b37;color:#eee9d8;border:1px solid #53675a;border-radius:7px;padding:10px 14px;font:inherit}button{cursor:pointer}button[aria-pressed=true]{background:#e7c274;color:#263528;border-color:#e7c274}button:focus-visible,select:focus-visible{outline:3px solid #eea652;outline-offset:3px}.modes{display:flex;gap:7px;flex-wrap:wrap;flex:1}.comparison{display:grid;grid-template-columns:1fr 1fr;gap:16px}figure{margin:0;background:#1c3430;border:1px solid #3e5548;border-radius:10px;overflow:hidden}figcaption{display:flex;justify-content:space-between;align-items:center;padding:12px 16px;color:#ced4c5;font-size:12px}figcaption strong{color:#f6e5b8;font-size:14px}.comparison img{display:block;width:100%;aspect-ratio:1.6;object-fit:contain;background:#10241f}.comparison.single{grid-template-columns:1fr}.comparison.single figure:first-child{display:none}.notes{display:flex;justify-content:space-between;gap:20px;color:#bac4b7;font-size:12px;margin:14px 0 32px}.palette{display:grid;grid-template-columns:repeat(5,1fr);gap:10px}.chip{display:flex;gap:12px;align-items:center;background:#203831;border-radius:6px;padding:10px}.chip i{display:block;width:48px;height:48px;border-radius:4px}.chip span{font-size:13px}.chip small{display:block;color:#acb9a8;font-size:10px;letter-spacing:.08em}.sources{margin-top:32px;border-top:1px solid #3e5548;padding-top:20px;display:flex;gap:24px;flex-wrap:wrap;font-size:13px}.sources p{max-width:760px;color:#bac4b7;margin:0}footer{margin-top:28px;color:#8fa497;font-size:12px}@media(max-width:850px){main{padding:24px 16px}.comparison{grid-template-columns:1fr}.palette{grid-template-columns:repeat(2,1fr)}.notes{display:block}button{padding:8px 10px}}
</style><main>
<header><div class="eyebrow">Swedish golf · Colour study · 13 September 2026</div><h1>A more colourful landscape.</h1>
<p>Deep grass greens, golden sand, blue water and a full autumn canopy. Actual application captures compare the earlier pale pass with the stronger Witness-inspired palette. <a href="puttom-day-review-noon.png">View the elevated Dag check at Puttom hole 2.</a></p></header>
<div class="toolbar"><label>Course<select id="course"><option value="puttom">Puttom · lake and forest</option><option value="upsala">Upsala · close trees</option><option value="angso">Ängsö · all five species</option></select></label>
<label>Compare with<select id="baseline"><option value="after">Earlier pale pass</option><option value="before">Original palette</option></select></label>
<div class="modes" id="modes"></div></div>
<div class="comparison" id="comparison"><figure><figcaption><strong id="beforeLabel">Earlier pale pass</strong><span>Click to open full size</span></figcaption><a id="beforeLink"><img id="before" alt="Previous application colour palette"></a></figure><figure><figcaption><strong>Vibrant palette</strong><span id="modeLabel"></span></figcaption><a id="afterLink"><img id="after" alt="Updated application colour palette"></a></figure></div>
<div class="notes"><span id="feeling"></span><span>Desktop WebGPU · identical camera per course · screenshots, not mockups</span></div>
<div class="eyebrow" style="margin-bottom:12px">Authored material pigments · lighting changes their appearance</div><div class="palette">${chips}</div>
<div class="sources"><p>Reference study: The Witness's environment work informed the colour grouping, broad foliage shading, warm stone and blue sky. These are our own material colours, tuned for the Swedish courses.</p><a href="https://www.fletcher.studio/blog/2017/5/26/the-witness-designing-video-game-environments">Fletcher Studio · Landscape</a><a href="https://www.artofluis.com/3d-work/the-art-of-the-witness/clouds/">Luis Antonio · Sky & clouds</a><a href="https://www.artofluis.com/3d-work/the-art-of-the-witness/agricultural-area-and-birch-forest/">Luis Antonio · Birch forest</a><a href="README.md">Research & validation notes</a></div>
<footer>The application keeps its existing tree models, placement and LOD geometry. The colour changes apply to Ghibli / Målad mode.</footer>
</main><script>
const profiles={noon:['Day','Leaf green, cobalt sky and warm sand.'],golden:['Evening','Honey light over rich greens and cool woodland shadows.'],dawn:['Dawn','Rose light and blue-lavender distance.'],midnight:['Midnight sun','Apricot light and violet-blue sky, with readable ground.'],bluehour:['Blue hour','Cobalt and indigo with subdued water highlights.'],storm:['Storm','Slate clouds and deep, cool greens.'],mist:['Mist','Silver light; colour remains visible in the foreground.'],host:['Autumn','Gold, orange and crimson against evergreen woodland.']};
let mode='noon';const get=id=>document.getElementById(id);
for(const [key,[label]] of Object.entries(profiles)){const b=document.createElement('button');b.textContent=label;b.dataset.mode=key;b.onclick=()=>{mode=key;update()};get('modes').append(b)}
function update(){const course=get('course').value,baseline=get('baseline').value;const single=course==='angso';get('comparison').classList.toggle('single',single);get('baseline').disabled=single;
for(const [id,phase] of [['before',baseline],['after','final']]){if(single&&id==='before')continue;const src=course+'-'+phase+'-'+mode+'.png';get(id).src=src;get(id+'Link').href=src}
get('beforeLabel').textContent=baseline==='after'?'Earlier pale pass':'Original palette';get('modeLabel').textContent=profiles[mode][0];get('feeling').textContent=profiles[mode][1];for(const b of get('modes').children)b.setAttribute('aria-pressed',String(b.dataset.mode===mode));}
get('course').onchange=update;get('baseline').onchange=update;update();
</script></html>`);
console.log(path.join(out,'index.html'));
